apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl
  labels:
    app: depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: depl
  template:
    metadata:
      labels:
        app: depl
    spec:
      containers:
      - name: itdt-frontend
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          value: "eva"
        - name: REACT_APP_COMPANY_NAME
          value: "itmo"
    
