apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: repl
  labels:
    app: repl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: repl
  template:
    metadata:
      labels:
        app: repl
    spec:
      containers:
      - name: itdt-frontend
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: confmap
              key: REACT_APP_USERNAME
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: confmap
              key: REACT_APP_COMPANY_NAME
   

